
<br/>

<?php 
$this->menutitle=" 婚介中心";

$this->left=
"<ul>
<li><a href='/admin/agent' class='link'><img
src='/images/icons/lock_edit.png' class='icon' />婚介列表 </a></li>
</ul>";

?>



 <b><i>婚介会员一览表 :</i></b>
<div class="hastable">
<table cellspacing="0">
	  <thead>
		<tr>
		<td width="12%">个人头像</td>
		<td width="1%">ID</td>
		<td width="30%">电邮</td>
		<td width="30%">简介</td>
		
		<td colspan="4">操作</td>
		</tr>
	  </thead>
	  <tbody>
		<?php foreach ($this->rows as $i=>$row): ?>
		  <tr>
		    <td>
		    <?php 
		    $logofile="upload_img/ids/".$row->id.".jpg";
		    if (file_exists($logofile)) {
		    echo "<img align='center' width='80' height='80' src='/upload_img/ids/".$row->id.".jpg'/>";
		    } else {
			echo "<img align='center' width='80' height='80' src='/images/caclass/default.jpg'/>";
		    }
		    ?>
		    </td>  
		    <td><?php echo $this->escape($row->id); ?></td> 
		    <td><?php echo $this->escape($row->email); ?></td> 
		    <td><?php 
		    $name="姓名：".$row->lname.$row->name;
		    $sex=Model_Sex::getName($row->sex);
		    if ($sex) {
			$name.='， 性别：'.$sex;
			}		    	
		    $date = new DateTime($row->birth);
		    $now = new DateTime();
		    $interval = $now->diff($date);
		    
		    $name.="， 年龄：$interval->y";
		    echo $name;
		    ?>
		    </td> 
		    
		    <td><a target="_blank" href="/agent/edit/id/<?php echo $row->id;?>">编辑</a></td>
		    <td>
		    <a target="_blank" href="/agent/preview/id/<?php echo $row->id;?>">预览</a>
		    </td>
		  </tr>
		<?php endforeach; ?>
	  </tbody>
	</table><br/>
	<?php
	echo $this->paginationControl($this->rows, 'Sliding', 'pagination.phtml');
	?>
</div>

