<div class="unit unit2">
<div class="title" style=""><span class="titletext">注册成功！</span></div>
<div class="unit_bc">
<div class="module">

您已登记注册成为我们的新会员！ 激活邮件已发送到您的邮箱，请使用电邮中提供的链接激活您的佳丽婚介网的账户，谢谢！ <br/><br/>

若有任何问题，请与我们的技术部联系。

<br/><br/>
联系人：郑生
<br/><br/>
联系电话： 647-891-2966
<br/><br/>
电邮：webfirm.ca@gmail.com

</div>
</div>
</div>



<style>
#bd {
padding:8px;
}
.module{
font-size:16px;
}

.module a{
color: blue;
}

</style>

