<?php $this->headTitle('佳丽婚介 - 联系我们'); ?>

<div class='pre_info plainContent'>

联系电话: <span>1-647-891-2966</span><br/><br/>
联系人: <span>郑生</span><br/>
----------------------------------------------------------------------<br>
电子邮箱 :<br><br>
一般事宜：hunjie.ca@gmail.com<br><br>
广告专用：hunjie.ca@gmail.com<br><br>
技术支持：webfirm.ca@gmail.com<br>

</div>

<div class='ok'>
<img src="/images/caclass/vip.jpg">
<a target="_blank" href='http://www.myca168.com'><img src="/images/caclass/ads168.jpg"></a>
</div>