<?php $this->headTitle('佳丽婚介'); ?>

<div class="unit unit2">
<div class="title" style=""><span class="titletext">工作流程说明</span></div>
<div class="unit_bc">
<div class="module">
<br/>
<span class='big'>所有注册会员经婚介所核实， 为您寻爱护航!</span>

<br/><br/>

我们是诚信严谨的婚介机构，要求会员认真对待爱情婚姻，本站大部分会员是由合作的婚介所推荐，婚介所对其真实性负责。<br/><br/>
在线免费注册会员，也要经婚介所核实后才能安排男女双方在安全的场所见面，无法亲临婚介办公室的,要经婚介所视频确认后，才能让双方进一步接触。<br/><br/>

注册会员的电话、电邮、姓名和出生日期不会公开显示。会员发短信，接受方会获得发送方电邮地址。<br/><br/>

申请订阅会员，可用paypal或信用卡付费。<br/><br/>

</div>
</div>
</div>

<div class='ok'>
<img src="/images/caclass/misc.jpg">
</div>
