<div class='back'><a href="javascript:window.close()">【关闭】</a></div>
<?php 


$this->menutitle=" 会员列表";

$this->left=
"<ul>
<li><a href='/agent/new' class='link'><img
src='/images/icons/user.png' class='icon' />添加新会员</a></li>
<li><a href='/agent/list' class='link'><img
src='/images/icons/lock_edit.png' class='icon' />会员列表 </a></li>
</ul>";

?>

<div class="hastable">
<?php echo "会员ID：{$this->user->id}, 会员姓名：{$this->user->lname} {$this->user->name}";?>
<table cellspacing="0">
	  <thead>
		<tr>
		<td width="10%">广告 ID</td>
		<td width="12%">起始日期</td>
		<td width="12%">截止日期</td>
		<td width="12%">订单日期</td>
		<td width="10%">月数</td>
		<td width="10%">金额</td>
		<td width='10%'>付款</td>
		<td>操作</td>
		</tr>
	  </thead>
	  <tbody>
		<?php foreach ($this->rows as $i=>$row): ?>
		  <tr>
		     
		    <td><?php echo $this->escape($row->id); ?></td> 
		    <td><?php echo $this->escape($row->start_date); ?></td> 
		    <td><?php echo $this->escape($row->end_date); ?>
		    </td> 
		    <td> <?php echo $row->inv_date ?></td> 
		    <td> <?php echo Model_Rate::getName($row->unit); ?></td> 
		    <td> <?php echo $row->amt ?></td> 
		    <td> 
		    <?php
		    if ($row->paid_flag==0) {
		    	echo "未付";
		    } else {echo "已付";}
		    ?>
		    </td> 
		    
		    <td></td>
		  </tr>
		<?php endforeach; ?>
	  </tbody>
	</table><br/>
	<?php
	echo $this->paginationControl($this->rows, 'Sliding', 'pagination.phtml');
	?>
</div>

<style>
.hastable table tr td {
text-align:center;
}	
	
</style>

