<?php 
$this->menutitle=" 会员列表";

$this->left=
"<ul>
<li><a href='/agent/new' class='link'><img
src='/images/icons/user.png' class='icon' />添加新会员</a></li>
<li><a href='/agent/list' class='link'><img
src='/images/icons/lock_edit.png' class='icon' />会员列表 </a></li>
</ul>";

?>

 <b><i> 本婚介所会员 :</i></b>
<div class="hastable">
<table cellspacing="0">
	  <thead>
		<tr>
		<td width="12%">个人头像</td>
		<td width="1%">ID</td>
		<td width="13%">电邮</td>
		<td>简介</td>
		<td width='8%'>订阅</td>
		
		<td colspan="4" width='8%'>操作</td>
		</tr>
	  </thead>
	  <tbody>
		<?php foreach ($this->rows as $i=>$row): ?>
		  <tr>
		    <td>
		    <?php 
		    $logofile="upload_img/ids/".$row->id.".jpg";
		    if (file_exists($logofile)) {
		    echo "<img align='center' width='80' height='80' src='/upload_img/ids/".$row->id.".jpg'/>";
		    } else {
			echo "<img align='center' width='80' height='80' src='/images/caclass/default.jpg'/>";
		    }
		    ?>
		    </td>  
		    <td><?php echo $this->escape($row->id); ?></td> 
		    <td><?php echo $this->escape($row->email); ?></td> 
		    <td><?php 
		    $name="姓名：".$row->lname.$row->name;
		    $sex=Model_Sex::getName($row->sex);
		    if ($sex) {
			$name.='， 性别：'.$sex;
			}		    	
		    $name.="， 身高(cm)：$row->height";

		    $date = new DateTime($row->birth);
		    $now = new DateTime();
		    $interval = $now->diff($date);
		    
		    $name.="， 年龄：$interval->y";
		    $education=Model_Education::getName($row->edu);
		    if ($education) {
		    $name.="， 学历：$education";
		    }
		    $mar=Model_Status::getName($row->marriage);
		    if ($mar) {
		    $name.="，婚姻状况:".$mar;	
		    }
		    
		    $cn=Model_Country::getName($row->country);
		    if ($cn) {
		    $name.="，现居住地：$cn".$row->city;
		    }
		    $nation=Model_Country::getName($row->nationality);
		    if ($nation) {
		    $name.="， 国籍：$nation";
		    }
		    $name.="， 职业：".$row->job;
		    $name.="， 注册日期：".$row->created_date;
		    echo $name;
		    
		    ?>
		    </td> 
		    <td> <?php 
		    if ($row->paid_flag==0) {
		    echo "不是"; 
		    }else {echo "是";}
		    ?></td> 
		    
		    <td><a href="/agent/edit/id/<?php echo $row->id;?>">编辑</a></td>
		    <td>
		    <a target="_blank" href="/agent/preview/id/<?php echo $row->id;?>">预览</a>
		    </td>
		  </tr>
		<?php endforeach; ?>
	  </tbody>
	</table><br/>
	<?php
	echo $this->paginationControl($this->rows, 'Sliding', 'pagination.phtml');
	?>
</div>

