<div class="maincontent">
<?php echo $this->form;?>
</div>

<?php 
$this->menutitle=" 管理中心";

$this->left=
"<ul>
<li><a href='/admin' class='link'><img
src='/images/icons/lock_edit.png' class='icon' />数据列表 </a></li>
<li><a href='/admin/master/sqn' class='link'><img
src='/images/icons/lock_edit.png' class='icon' />特别推荐会员 </a></li>	
<li><a href='/admin/master/order' class='link'><img
src='/images/icons/lock_edit.png' class='icon' />特别推荐排序 </a></li>				
</ul>";

?>
