<br/>
<?php echo "登录电邮：",$this->row->email," <br/>会员名字：",$this->row->name;?><br/>
<?php echo $this->form; ?>

<?php 
$this->menutitle="婚介中心";
$this->left=
"<ul>
<li><a href='/admin' class='link'><img
src='/images/icons/lock_edit.png' class='icon' />数据列表 </a></li>
<li><a href='/admin/master/sqn' class='link'><img
src='/images/icons/lock_edit.png' class='icon' />特别推荐会员 </a></li>
<li><a href='/admin/master/order' class='link'><img
src='/images/icons/lock_edit.png' class='icon' />特别推荐排序 </a></li>
</ul>";
?>
