<?php 
$this->menutitle="档案资料";
$this->left=$this->profile();
?>
<a class='back' href="javascript:window.close();">【关闭窗口】</a>
<br/>
<br/>
<br/>
发送者姓名：
<?php 
$mid=$this->msg->sid;
$mobj=Model_Member::getUserById($mid);
echo $mobj->lname,$mobj->name;
?>


&nbsp;&nbsp;&nbsp;
短信发送日期：<?php echo $this->msg->created_date; ?>

&nbsp;&nbsp;&nbsp;
<a target="_blank" href="/index/show/id/<?php echo $mid;?>">【查看发送者档案】</a>

<div class="hastable">
<table cellspacing="0">
		<tr>
		<td width="10%">标题</td>
		<td><?php echo $this->msg->title;?></td>
		</tr>
		<tr>
		<td>信息</td>
		<td><?php echo $this->msg->content;?></td>
		</tr>
</table>		
</div>

<style>
.hastable {
width:95%;
margin-right:10px;
}
</style>
