<div class='sel'>
	<div id="loginfm"><?php echo $this->loginfm;?>
  	</div>
 </div>

	<div class="logo_banner">
	<!-- 
        <a href="/" id="logo"><img src="/images/caclass/logo.jpg" alt="eda58.com"></a> 
		<span class='banner1'><img src="/images/caclass/banner.jpg"></span>
		-->
		<span class='hunjie'><img src="/images/caclass/hunjie.jpg"></span>
    </div>
   <div class='cls'></div>
   
	<div class='topnav'>
	
	<?php echo $this->navigation()->menu()->setMaxDepth(0);?>
	
</div>